# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: nitroshkin/db-library:${APP_VERSION}
    container_name: library_db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${LIBRARY_PG_PASSWORD}
      POSTGRES_USER: dev
      POSTGRES_DB: libraryservice
      PGDATA: /home/data
      POSTGRES_INITDB_ARGS: "-A md5"
    expose:
      - 5433
    ports:
      - "54322:5432"
    volumes:
      - pg_data_volume:/data/lib/postgresql/data

  server:
    image: nitroshkin/service-library:${APP_VERSION}
    container_name: library
    expose:
     - 8060
    ports:
      - "8060:8060"
    depends_on:
      - db
      - kafka
    restart: unless-stopped
    
       
  zookeeper:
    image: zookeeper:3.7.0
    container_name: zookeeper
    restart: "no"
    ports:
      - "2181:2181"

  kafka:
    image: obsidiandynamics/kafka
    container_name: kafka
    restart: "no"
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: DOCKER_INTERNAL:PLAINTEXT,DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: DOCKER_INTERNAL://:9092,DOCKER_EXTERNAL://:29092
      KAFKA_ADVERTISED_LISTENERS: DOCKER_INTERNAL://kafka:9092,DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:9092"
    depends_on:
      - "kafka"
  
  keycloak_lib:
    image: quay.io/keycloak/keycloak:25.0.4
    container_name: keycloak_lib
    restart: "no"
    ports:
      - "8081:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    volumes:
      - keycloak_data:/opt/keycloak/data/import
   
volumes:
  pg_data_volume:
  keycloak_data:



