---
apiVersion: v1
kind: Service
metadata:
  name: kafdrop
spec:
  ports:
  - port: 80
    targetPort: 9000
    nodePort: 30009
  selector:
    app: kafdrop
  type: LoadBalancer
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: kafdrop-env-config
data:
  KAFKA_BROKERCONNECT: "kafka:9092"
  SERVER_PORT: "9000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafdrop
  labels:
    app: kafdrop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafdrop
  template:
    metadata:
      labels:
        app: kafdrop
    spec:
      containers:
      - name: kafdrop
        image: obsidiandynamics/kafdrop
        envFrom:
        - configMapRef:
            name: kafdrop-env-config
        ports:
        - containerPort: 9000
          name: kafdrop-port
        imagePullPolicy: Always
